#ifndef H_CONSTANTS
#define H_CONSTANTS

#define CHANNEL_COMMAND 0x00
#define CHANNEL_SHELL   0x01

#define COMMAND_TERMINAL_OPEN  0x00
#define COMMAND_TERMINAL_CLOSE 0x01
#define COMMAND_TERMINAL_SIZE  0x02

#endif