#ifndef H_CONSTANTS
#define H_CONSTANTS

#define CHANNEL_COMMAND 0x00
#define CHANNEL_SHELL   0x01

#define COMMAND_TERMINAL_TERM  0x00
#define COMMAND_TERMINAL_SIZE  0x01

#define SERVER_AUTO_TERM 0x1

#endif